image: registry.gitlab.com/gbraad/byo-atomic:latest

pages:
  script:
  #- polipo
  #- pushd /srv/repo
  #- python -m SimpleHTTPServer &
  #- popd
  - pushd /home/working
  #- rpm-ostree compose tree --proxy=http://127.0.0.1:8123 --repo=/srv/repo sig-atomic-buildscripts/centos-atomic-host.json
  - rpm-ostree compose tree --repo=/srv/repo sig-atomic-buildscripts/centos-atomic-host.json
  - popd
  - mv /srv/repo public
  artifacts:
    paths:
    - public
  only:
    - master
