#!/usr/bin/env ansible-playbook
---
- hosts: localhost

  tasks:
  - name: Clone CentOS-Atomic buildscripts
    git: >-
      repo=https://github.com/CentOS/sig-atomic-buildscripts
      version=downstream
      depth=1
      dest=/workspace/centos-atomic

  - name: Compose CentOS-Atomic tree
    command: >-
      chdir=/workspace/centos-atomic/
      rpm-ostree compose tree --repo=/srv/repo ./centos-atomic-host.json
